---
title             : "Non-word repetition in Yélî Dnye"
shorttitle        : "NWR in Yélî Dnye"

author: 
  - name          : "Alejandrina Cristia"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "29, rue d’Ulm, 75005 Paris, France"
    email         : "alecristia@gmail.com"
  - name          : "Marisa Casillas"
    affiliation   : "2"
    address       : "Wundtlaan 1, 6525 XD, Nijmegen, The Netherlands"
    email         : "marisa.casillas@mpi.nl"

affiliation:
  - id            : "1"
    institution   : "Laboratoire de Sciences Cognitives et de Psycholinguistique, Département d'Etudes cognitives, ENS, EHESS, CNRS, PSL University"
  - id            : "2"
    institution   : "Max Planck Institute for Psycholinguistics"

authornote: |
  All data are made available in a repository in the Open Science Framework. AC acknowledges the support of the Agence Nationale de la Recherche (ANR-17-CE28-0007 LangAge, ANR-16-DATA-0004, ANR-14-CE30-0003, ANR-17-EURE-0017); and the J. S. McDonnell Foundation Understanding Human Cognition Scholar Award. 

abstract: >
   In nonword repetition (NWR) studies, participants are presented auditorily with an item that is phonologically legal but lexically meaningless in the local language. Accuracy is thought to reflect long-term phonological knowledge as well as online phonological working memory and flexible production patterns.In this study, we report on NWR results among children learning Yêly Dnyé, an isolate spoken in Rossel Island, PNG, with an unusually dense phonological inventory. This study contributes to three lines of research. First, we document that non-word items containing typologically rare sounds are repeated accurately less often that non-words containing more common sounds. Second, we document rather weak effects of item length, contributing to other research suggesting that length effects may be language-specific. Third, we do not find strong individual variation effects in this population, contrary to previous results documenting strong age-related effects. Together, these data provide a unique view of online phonological processing in a seldom-studied language, and contribute to both typological and language acquisition research.




keywords          : "phonology, non-word repetition, development"
wordcount         : "~xxx words"

bibliography      : ["nwrbib.bib"]

figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            :
  papaja::apa6_pdf:
    latex_engine: xelatex
    includes:
      in_header: header.tex
---

<!--
-->

The Yélî sound system, much like its baroque grammatical system in general [STEVE_GRAMMAR_REF], is unlike any other in the region, with 90 contrastive segments, including at least two contrasts not yet been documented elsewhere (labial-coronal double-articulations with dental vs. post-alveolar coronal placement in both oral and nasal stops) [STEVE_GRAMMAR_REF]. With only four primary places of articulation (bilabial, alveolar, post-alveolar, and velar) and no voicing contrasts, the phonological inventory is remarkably packed with acoustically similar segments. The core oral stop set includes both singleton (/p/, /t/, /ṭ/, and /k/) and doubly-articulated (/tp/, /ṭp/, /kp/) segments, with full nasal equivalents (/m/, /n/, /ṇ/, /ŋ/, /nm/, /ṇm/, /ŋm/), and with a substantial portion of these able to be pre-nasalized or nasally released (/mp/, /nt/, /ṇṭ/, /ŋk/, /nmtp/, /ṇmṭp/, /ŋmkp/, /ṭṇ/, /kŋ/, /ṭpṇm/, /kpŋm/). Finally, a number of these can also be labialized or palatalized on the release, or both (/pʲ/, /tʃ/, /tpʲ/, /ṭʲ/, /ṭpʲ/, /kʲ/, /kpʲ/, /pʲʷ/, /mbʲ/, /ndʒ/, /nmdbʲ/, /ṇḍʲ/, /ṇmḍbʲ/, /mbʷ/, /ŋɡʷ/, /mbʲʷ/, /ṭṇʲ/, /ṭpṇmʲ/, /kŋʷ/, /mʲ/, /nʲ/, /nmʲ/, /ṇʲ/, /ṇmʲ/, /mʷ/, /ŋʷ/, mʲʷ/). Among the remaining consonants are small group of oral continuants (/w/, /j/, /ɣ/, /l/, /βʲ/, /lʲ/, /lβʲ/). Vowels in Yélî Dnye may be oral or nasal, short or long. The 10 oral vowel qualities (/i/, /ɯ/, /u/, /e/, /o/, /ə/, /ɛ/, /ɔ/, /æ/, /ɑ/) can be produced as short or long vowels, with 7 of these able to appear as short and long nasal vowels as well (/i/, /u/, /ə/, /ɛ/, /ɔ/, /æ/, /ɑ/). In total, Levinson [STEVE_GRAMMAR_REF] then counts 90 distinctive segments in Yélî Dnye (93 when including consonants that are extremely rarely used).

TESXwdfkh ɔ TESdfkjah
grwerg /kʲ/, /kpʲ/, /pʲʷ/, /mbʲ/, /ndʒ/, /nmdbʲ/, /ṇḍʲ/, /ṇmḍbʲ/, /mbʷ/, /ŋɡʷ/, /mbʲʷ/, /ṭṇʲ/, /ṭpṇmʲ/, /kŋʷ/, /mʲ/, /nʲ/, /nmʲ/, /ṇʲ/, /ṇmʲ/, /mʷ/, /ŋʷ/, mʲʷ/). Among the remaining consonants are small group of oral continuants (/w/, /j/, /ɣ/, /l/, /βʲ/, /lʲ/, /lβʲ/) sdgfdfg


\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
